from . import start
from . import cancel
from . import main_menu
from . import about
from . import contacts
from . import question_answer
from . import review
from . import yoga_button
from . import collection
